// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvFHHrjAyxaW49CPzg6doj8yDk8ZXdFfs',
    appId: '1:94785060900:web:79b9732034671756ec98b1',
    messagingSenderId: '94785060900',
    projectId: 'chanudhi-aluthge',
    authDomain: 'chanudhi-aluthge.firebaseapp.com',
    storageBucket: 'chanudhi-aluthge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_eyrrCe1G-nmBiJVOZV_NcG81oqotRw8',
    appId: '1:94785060900:android:357720260581735fec98b1',
    messagingSenderId: '94785060900',
    projectId: 'chanudhi-aluthge',
    storageBucket: 'chanudhi-aluthge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh2BEak-ck3sWRVFkKGuAueOw3nXTUgiA',
    appId: '1:94785060900:ios:71a0dc7ca9d62734ec98b1',
    messagingSenderId: '94785060900',
    projectId: 'chanudhi-aluthge',
    storageBucket: 'chanudhi-aluthge.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh2BEak-ck3sWRVFkKGuAueOw3nXTUgiA',
    appId: '1:94785060900:ios:71a0dc7ca9d62734ec98b1',
    messagingSenderId: '94785060900',
    projectId: 'chanudhi-aluthge',
    storageBucket: 'chanudhi-aluthge.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvFHHrjAyxaW49CPzg6doj8yDk8ZXdFfs',
    appId: '1:94785060900:web:afb63df442e6a82bec98b1',
    messagingSenderId: '94785060900',
    projectId: 'chanudhi-aluthge',
    authDomain: 'chanudhi-aluthge.firebaseapp.com',
    storageBucket: 'chanudhi-aluthge.firebasestorage.app',
  );
}
