// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your api key',
    appId: 'your app id',
    messagingSenderId: 'your messaging sender id',
    projectId: 'your project id',
    authDomain: 'your  auth domian',
    storageBucket: 'your storage bucket',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your api key',
    appId: 'your app id',
    messagingSenderId: 'your messaging sender id',
    projectId: 'your project id',
    storageBucket: 'storage bucket',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your api key',
    appId: 'your app id',
    messagingSenderId: 'your messaging sender id',
    projectId: 'your project id',
    storageBucket:'your-storage bucket',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your api key',
    appId: 'your app id',
    messagingSenderId: 'your messaging sender id',
    projectId: 'your project id',
    storageBucket:'your-storage bucket',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your api key',
    appId: 'your app id',
    messagingSenderId: 'your messaging sender id',
    projectId: 'your project id',
    authDomain: 'your domain',
    storageBucket: 'your-storage bucket',
  );
}
